service:
  traffic_images_url: https://api.data.gov.sg/v1/transport/traffic-images/
  tomtom_key: bId63y2w4uPBRnpIvmnYn8jwbTUhEEmR
  tomtom_route_url: https://api.tomtom.com/routing/1/calculateRoute/
  tomtom_traffic_url: https://api.tomtom.com/traffic/services/4/flowSegmentData/relative0/10/
  baidu_url: https://aip.baidubce.com/rest/2.0/image-classify/v1/vehicle_detect?access_token=24.0fc731ae4c8138e6eefcaf3eb274ea01.2592000.1691808843.282335-36100278